### ISSUE TITLE
Question: HookupExternalGitRepo

### ISSUE THREAD

**Issue by dfinke** [davidebbo/AzureWebsitesSamples#10]
Can this connect a VSTS git repo to an Azure App Service?

**Comment by davidebbo** [comment]
Not sure what you are referring to, as this repo contains a bunch of different samples. Please use https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview or StackOverflow for general APp Service questions not directly related to one of the samples.
