### ISSUE TITLE
Unable to add HostNames or SSL binding to sites

### ISSUE THREAD

**Issue by trailmax** [davidebbo/AzureWebsitesSamples#2]
I'm executing this sample, but unable to get host names added to a site and SSL bindings are impossible to add. Function `BindCertificateToSite` is getting executed, but no change to the site happens. 

And I can manually add the host binding and SSL cert to that site, but unable to do it programmatically. 

Any ideas?

**Comment by davidebbo** [comment]
@x10shun this is the part of the sample you added. Do you know what might be going on?

**Comment by naveedaz** [comment]
This was a bug in the sample. Please add set property HostNameSslState.ToUpdate = true, before calling the CreateOrUpdateSite in BindCertificateToSite. I am fixing the sample to reflect that.

**Comment by trailmax** [comment]
Sorry, but that still does not work. If I add domain binding manually and add `ToUpdate=true` then yes. But in the current state I get error:

> Response: 404 Not Found 
> Hostname 'blah.com' does not exist

I've tried adding just domain name binding without SSL and that does not happen - which explains the error. Any other ideas?

I've found `websiteClient.Sites.CreateOrUpdateSiteHostNameBindingAsync` - is it not supposed to add domain name binding? but I could not find any documentation on how to use it.

**Comment by trailmax** [comment]
I'm sorry again, I stand corrected. SSL binding does not work even if I manually add the domain. 

When I get site object back from `websiteClient.Sites.CreateOrUpdateSite()`, I inspect `HostNameSslStates` object and I see 3 objects there - 2 for `mysite.azurewebsites.net` and `mysite.scm.azurewebsites.net` and third for the one I've just added, but in all 3 (including the new one) I see `SslState: Disabled`. 

In debugging this looks like this:

```
{Microsoft.Azure.Management.WebSites.Models.HostNameSslState}
    Name: "subdomain.mydomaincom"
    SslState: Disabled
    Thumbprint: null
    ToUpdate: null
    VirtualIP: null
```

I suspect this is the same issue I'm seen using the older management library: https://github.com/Azure/azure-sdk-for-net/issues/1461

Any other ideas? Is that server-side issue, not the library/sample?

**Comment by trailmax** [comment]
I have managed to get it working. Host names are to be added by `CreateOrUpdateSiteHostNameBindingAsync()` rather than `site.HostNames`:

```
        var binding = new HostNameBinding()
        {
            Location = "North Europe",
            Name = hostName,
            CustomHostNameDnsRecordType = CustomHostNameDnsRecordType.CName,
            HostNameType = HostNameType.Verified,
            SiteName = siteName,
            Type = "Microsoft.Web/sites/hostNameBindings",
        };
        var result = await websiteClient.Sites.CreateOrUpdateSiteHostNameBindingAsync(resourceGroupName, siteName, hostName, binding);
        site = websiteClient.Sites.GetSite(resourceGroupName, siteName);

        site.HostNameSslStates.Add(new HostNameSslState
        {
            Name = hostName,
            Thumbprint = certificate.Thumbprint,
            SslState = SslState.SniEnabled,
            ToUpdate = true,
        });

        site = await websiteClient.Sites.CreateOrUpdateSiteAsync(resourceGroupName, siteName, site);
```

Though I'm not sure about all the parameters in `HostNameBinding` object are required. Can you please verify what properties are required there? (I took the values from Resource Explorer)
