### ISSUE TITLE
Deploy Timer Trigger Function?

### ISSUE THREAD

**Issue by dfinke** [davidebbo/AzureWebsitesSamples#7]
Do you have a function similar to the below for deploying timer triggers? I replaced the `$props` with a PS hashtable that defined the the Timer Trigger JSON. Then it failed on on the call to `New-AzureRMResource`.

https://github.com/davidebbo/AzureWebsitesSamples/blob/master/PowerShell/HelperFunctions.ps1#L367

**Comment by davidebbo** [comment]
Try simply changing the trigger to be a timer trigger. Exactly the same difference as what you see in functions.json in the two cases if you create functions from portal.

e.g. binding.json

```
  "bindings": [
    {
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 0 0 */3 * *"
    }
  ]
```

(just convert to PS syntax)

**Comment by dfinke** [comment]
Thank you. Yeah, I tried that. The `New-AzureRMResource` threw an error. I'll try again.

**Comment by dfinke** [comment]
Here is the error I get.
```
New-AzureRmResource : NotFound : System.IO.FileNotFoundException: Function (TimerTriggerPS) config does not exist or is invalid
   at Kudu.Core.Functions.FunctionManager.<GetFunctionConfigAsync>d__8.MoveNext()
```

**Comment by davidebbo** [comment]
And does the exact case I have in my sample file work for you?

**Comment by dfinke** [comment]
Yes, that works. I'll keep digging.
