### ISSUE TITLE
[Question] How to list the slots for a web app using the “scm.azurewebsites.net” url

### ISSUE THREAD

**Issue by dfinke** [davidebbo/AzureWebsitesSamples#9]
Hi,

I was not sure where to post this or who I could follow with.

https://stackoverflow.com/questions/46796063/how-to-list-the-slots-for-a-web-app-using-the-scm-azurewebsites-net-url

Thank you

**Comment by davidebbo** [comment]
StackOverflow is a good place for this, but you should add the azure-web-sites tag to make sure it gets seen by the right people.
